version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio_backend
    restart: always
    ports:
      - "5001:5000"
    env_file:
      - .env
    networks:
      - portfolio_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:5001/api}
    container_name: portfolio_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - portfolio_net

networks:
  portfolio_net:
    driver: bridge
